name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: terraform-deploy
  cancel-in-progress: false

permissions:
  id-token: write   # Required for requesting the JWT token from GitHub OIDC
  contents: read    # Required for actions/checkout

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the GitHub repository code onto the runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Authenticate with AWS via OIDC
      # Replace the role ARN with your exact AWS IAM Role ARN configured for OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::560396668922:role/GitHubActionsWorkflowRole
          aws-region: ap-south-2

      # Step 3: Set up the Terraform CLI tool on the runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

     # Step 4: Format check
      - name: Terraform Format Check
        run: terraform fmt -check -diff

      # Step 5: Initialize the workspace (uses OIDC credentials to access the S3 backend)
      - name: Terraform Init
        run: terraform init

      # Step 6: Validate the syntax
      - name: Terraform Validate
        run: terraform validate

      # Step 7: Generate an execution plan
      - name: Terraform Plan
        run: terraform plan -input=false

      # Step 8: Apply changes automatically on main branch push
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
